language: go
install: true
sudo: required
# test stage automatically added for each go version
go:
  - 1.12.x
  - master
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
# script used in the automatically added test stage
script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.13
  - $(go env GOPATH)/bin/goveralls -service=travis-ci
  - 'if [ "${JOB}" = "test" ]; then make test; fi'
  - 'if [ "${JOB}" = "lint" ]; then make lint; fi'
  - 'if [ "${JOB}" = "integration" ]; then make integration; fi'
 
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.11
    - IMAGE_NAME=tsuru/api
  matrix:
    - JOB=test
    - JOB=lint
    - JOB=integration
jobs:
  fast_finish: true
  allow_failures:
    - go: master
  exclude:
    - go: master
      env: JOB=test
    - go: master
      env: JOB=lint
    - go: master
      env: JOB=integration
notifications:
  email:
    on_success: change
    on_failure: always